modLoader="kotlinforforge"
loaderVersion="[5.7,)"

license="CC0-1.0"

issueTrackerURL="https://github.com/kphrx/villager-inventory-hwyla-plugin/issues"

[[mods]]
modId="villager_inventory_hwyla_plugin"
version="${version}"
displayName="Villager Inventory Plugin for Hwyla forks"
updateJSONURL="https://api.modrinth.com/updates/ESa9RivE/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/mod/villager-inventory-hwyla-plugin"
authors="kPherox"
description='''
Show villager's inventory slots to tooltip.
'''

[[dependencies.villager_inventory_hwyla_plugin]]
modId="minecraft"
type="required"
versionRange="[${minecraft},)"
ordering="NONE"
side="BOTH"

[[dependencies.villager_inventory_hwyla_plugin]]
modId="jade"
type="optional"
versionRange="[${jadeneoforge},)"
ordering="NONE"
side="BOTH"

[[dependencies.villager_inventory_hwyla_plugin]]
modId="wthit"
type="optional"
versionRange="[${wthit},)"
ordering="NONE"
side="BOTH"
