[versions]
kotlin = "2.3.10"
ktfmt = "0.25.0"
fabric-loom = "1.14-SNAPSHOT"
minotaur = "2.+"
minecraft = "26.1-snapshot-1"
fabric-loader = "0.18.3"
fabric-kotlin = "1.13.9+"
jade = "26.0.0+fabric"
wthit = "fabric-18.0.0"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { group = "maven.modrinth", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
wthit = { group = "maven.modrinth", name = "wthit", version.ref = "wthit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[bundles]
fabric = ["fabric-loader", "fabric-language-kotlin"]
