[versions]
kotlin = "2.3.0"
ktfmt = "0.25.0"
fabric-loom = "1.14-SNAPSHOT"
minotaur = "2.+"
minecraft = "1.21.6"
fabric-loader = "0.16.14"
fabric-kotlin = "1.13.8+kotlin.2.3.0"
jade = "19.0.1+fabric"
wthit = "fabric-16.0.0"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { group = "maven.modrinth", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
wthit = { group = "maven.modrinth", name = "wthit", version.ref = "wthit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[bundles]
fabric = ["fabric-loader", "fabric-language-kotlin"]
