name: format
on:
  pull_request:
    branches: [master]
    paths:
    - '**/*.kts'
    - '**/*.kt'

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: setup jdk
        uses: actions/setup-java@46c56d6f92c88cf540acf95a12a4a41197499222 # v5.0.0+5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v5
      - name: format
        run: ./gradlew ktfmtFormat
      - name: suggester / ktfmt
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: ktfmt
